spring.application.name=foodChain

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/foodchain}
spring.datasource.username=${DB_USERNAME:innye}
spring.datasource.password=${DB_PASSWORD:$foodchain15}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
